## **assignment 2**

In [ ]:
import numpy as np

Q1

In [ ]:
list1= np.random.randint(0,40000,(65000,10000))

Q2

In [ ]:
print("The original list : " + str(list1))

res = dict(zip(list1[0], list1[1:]))
print("The Assigned Matrix : " + str(res))

The original list : [[14521 28992 16400 ... 17766  2615 12600]
 [26952 35971 34520 ... 10946 20078 30895]
 [13244 32186 11961 ... 37288 10145 33585]
 ...
 [25656 24464  9799 ... 17013 39206 22182]
 [32372 36522 12632 ... 22091 22586 39178]
 [36026 26435 39001 ... 39300 15221 35565]]
The Assigned Matrix : {14521: array([26952, 35971, 34520, ..., 10946, 20078, 30895]), 28992: array([11001, 17633,  9799, ..., 29030, 29438, 36791]), 16400: array([32437, 14440,  3206, ..., 25938, 18210, 23418]), 708: array([39037, 37288, 15156, ...,  9398, 32240, 38242]), 25051: array([36761, 24080, 14164, ..., 15985,  2616, 14511]), 14342: array([22004, 18047,  4166, ..., 30869,  1040,  3814]), 16274: array([37136, 10293, 26579, ...,  7253,  5940, 19200]), 25635: array([ 5826, 33484, 19122, ..., 19125, 19731, 26111]), 17583: array([24334, 39877, 21142, ..., 28199,  3806, 37271]), 34519: array([33773, 25571, 21500, ..., 22088,  9952,  5091]), 11801: array([17612,  8439, 16960, ..., 16094, 35864, 16923]), 14

In [ ]:
M = np.array(list1)
M[:,-5:]


array([[14488, 34102, 34488,  9955, 20742],
       [ 7123,  9027, 13194, 32900,  6267],
       [ 8863, 14018, 38257, 37628, 29065],
       ...,
       [35468,  9836, 28774, 35815, 11171],
       [29739,  1879, 31401, 22851, 23228],
       [36543,  7823,  4925,  8873,   752]])

In [ ]:
N = np.array(list1)
N[-2:,-5:]

array([[21515, 25774, 17739,  9400, 16844],
       [ 1843, 37680, 11622,   497, 10862]])

Q3

In [ ]:
from itertools import groupby

In [ ]:
print("The original list : " + str(N))

res = [list(val) for key, val in groupby(sorted(N))]
print("Matrix after grouping : " + str(res))


The original list : [[14036  9411 31961 ... 35411 20251  4147]
 [ 1139 36924 31095 ... 31395 31369 14403]
 [36555 10156 12401 ... 33811 22846 18807]
 ...
 [12791 14919 38895 ... 34027 14252 17731]
 [30588 10041  6204 ...  8981 37273 25658]
 [11173  8140  2262 ... 30372 34374 30887]]


ValueError: ignored

Q4

In [ ]:
N = np.array(list1)
matrix1 = N[-2:,-5:]
matrix2 = N[-2:,-5:]
rmatrix = [[0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0]]


for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        rmatrix[i][j] = matrix1[i][j] + matrix2[i][j]

for r in rmatrix:
    print(r)


for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        rmatrix[i][j] = matrix1[i][j] - matrix2[i][j]

for r in rmatrix:
    print(r)

[30944, 49600, 19166, 17204, 66656]
[56398, 61932, 31576, 61808, 24522]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


Q5

In [ ]:
import itertools


def sub_mat_even(n):
	
	temp = itertools.count(1)
	
	l = [[next(temp)for i in range(n)]for i in range(n)]
	

	if n%2 == 0:
		for i in range(0,len(l)):
			if i%2 == 1:
				l[i][:] = l[i][::-1]
	
	for i in range(n):
		for j in range(n):
			print(l[i][j],end=" ")
		print()

n = 4
sub_mat_even(n)


1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 


Q6

In [ ]:
K = np.array(list1)
l = K[-1:,-3:]

print("The original list is : " + str(l))


les = [6, 7, 8]

res = [[sub + (les[idx], ) for sub in val] for idx, val in enumerate(l)]

print("The matrix after row elements addition : " + str(res))


The original list is : [[27614 25081 28421]]
The matrix after row elements addition : [[array([27620]), array([25087]), array([28427])]]


## **assigment 3**

Q1

In [ ]:
sum(list1)

array([1303377788, 1302734493, 1303771047, ..., 1303416085, 1289967791,
       1301278174])

Q2

In [ ]:
list_1=np.random.randint(0,50,50)
print(list1)

[[ 2100 31718 38275 ... 15119 17641  4780]
 [  680 39259 20228 ...  5390  3353  9427]
 [31127 35677 17076 ... 22013 19744 22700]
 ...
 [23974  3155 21833 ... 21755  6431 10524]
 [27151  8923 13453 ... 10108 36521 20969]
 [20034 18955 27630 ...  3740 15858 37666]]


In [ ]:
max(list1)


ValueError: ignored

## **assignment 4**